### ISSUE TITLE
Missing validation

### ISSUE THREAD

**Issue by szefoo** [ggelashvili/expennies#1]
Hi! I think that the validation is here missing.

```
if (! $v->validate()) {
    throw new ValidationException($v->errors());
}
```

https://github.com/ggelashvili/expennies/blob/d0d94c4846ca6e879aa88343c8af5083e3861975/app/Controllers/AuthController.php#L75

**Comment by ggelashvili** [comment]
Yup, it is fixed in next video which is scheduled (not yet released) where we refactor the validation. Good catch 👍

**Comment by ggelashvili** [comment]
Yup, it is fixed in next video which is scheduled (not yet released) where we refactor the validation. Good catch 👍
