### ISSUE TITLE
npm install issue in docker

### ISSUE THREAD

**Issue by rajsarky** [ggelashvili/expennies#5]
<img width="326" alt="Screenshot 2024-03-11 at 17 13 18" src="https://github.com/ggelashvili/expennies/assets/77641848/f1016bde-cdc0-4ee1-b1b2-44006702590f">

kai@95053e6d82a9:/var/www$ npm install
bash: npm: command not found

**Comment by rajsarky** [comment]
kai@95053e6d82a9:/var/www$ node -v
v18.19.0


FROM php:8.1-fpm

ARG USER
ARG USER_ID
ARG GROUP_ID

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    curl \
    vim \
    libicu-dev

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash \
    && apt-get install nodejs -y

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-configure intl
RUN docker-php-ext-install pdo pdo_mysql intl

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY xdebug.ini "${PHP_INI_DIR}/conf.d"

RUN groupadd --force -g $GROUP_ID $USER
RUN useradd -ms /bin/bash --no-user-group -g $GROUP_ID -u 1337 $USER
RUN usermod -u $USER_ID $USER

USER $USER

**Comment by ggelashvili** [comment]
Yea you can add node to the Dockerfile or simply run `npm install` outside of docker container on your host
