### ISSUE TITLE
Updated packages and had issues with symphony-webpack-encore

### ISSUE THREAD

**Issue by Midstackdev** [ggelashvili/expennies#9]
Having issues with assets on twig after updating to latest versions 

`
    {{ encore_entry_link_tags('app') }}
    {{ encore_entry_script_tags('app') }}
`

throw this error after the update:

`
  Details
  Type: Twig\Error\RuntimeError
  Code: 0
  Message: An exception has been thrown during the rendering of a template ("The build "_default" is not configured").
  File: /var/www/resources/views/layout.twig
  Line: 10
`

After updating the `container_bindings.php` with this:

`
  'webpack_encore.tag_renderer' => fn(ContainerInterface $container) => new TagRenderer(
        new EntrypointLookupCollection($container,  BUILD_PATH . '/entrypoints.json'),
        $container->get('webpack_encore.packages')
    ),
`

**Comment by ggelashvili** [comment]
Yea most likely its not compatible with latest version. Feel free to open a PR and I'll review & merge it.
